version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      pip-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3
