name: gate-seal

plugins:
  - name: vyper
    version: 0.8.9
  - name: hardhat
    version: 0.8.5
  - name: infura  
    version: 0.8.4

compile:
  exclude:
    - contracts/GateSeal.vy
    - contracts/GateSealFactory.vy

compiler:
  vyper:
    version: 0.4.2
    evm_version: cancun

ethereum:
  default_network: local
  local:
    default_provider: hardhat

hardhat:
  hardhat_config_file: ./hardhat.config.js
  fork:
    ethereum:
      hoodi:
        upstream_provider: infura
      mainnet:
        upstream_provider: infura
