ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"

MIN_SEALABLES = 1
MAX_SEALABLES = 8

SECONDS_PER_DAY = 60 * 60 * 24

MIN_SEAL_DURATION_DAYS = 11
MIN_SEAL_DURATION_SECONDS = SECONDS_PER_DAY * MIN_SEAL_DURATION_DAYS

MAX_SEAL_DURATION_DAYS = 21
MAX_SEAL_DURATION_SECONDS = SECONDS_PER_DAY * MAX_SEAL_DURATION_DAYS

# GateSeal lifetime must be between 6 months and 2 years
MIN_LIFETIME_DURATION_DAYS = 180
MIN_LIFETIME_DURATION_SECONDS = SECONDS_PER_DAY * MIN_LIFETIME_DURATION_DAYS

MAX_LIFETIME_DURATION_DAYS = 730
MAX_LIFETIME_DURATION_SECONDS = SECONDS_PER_DAY * MAX_LIFETIME_DURATION_DAYS

# Total lifetime of GateSeal is fixed at 5 years
TOTAL_LIFETIME_DAYS = 365 * 5
TOTAL_LIFETIME_SECONDS = SECONDS_PER_DAY * TOTAL_LIFETIME_DAYS

# Prolongation window opens two months before expiry and lasts 7–14 days
PROLONGATION_OFFSET_DAYS = 60
PROLONGATION_OFFSET_SECONDS = SECONDS_PER_DAY * PROLONGATION_OFFSET_DAYS

MIN_PROLONGATION_WINDOW_DAYS = 7
MIN_PROLONGATION_WINDOW_SECONDS = SECONDS_PER_DAY * MIN_PROLONGATION_WINDOW_DAYS

MAX_PROLONGATION_WINDOW_DAYS = 14
MAX_PROLONGATION_WINDOW_SECONDS = SECONDS_PER_DAY * MAX_PROLONGATION_WINDOW_DAYS

MAINNET_ID = 1
GOERLI_ID = 5
HOLESKY_ID = 17000
HOODI_ID = 560048

MAX_PROLONGATIONS = 10
